name = "ao3-summary-bot"
main = "./src/server.js"
compatibility_date="2023-05-18"
node_compat = true

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# AO3_MICROSERVICE_URL
# AO3_SUMMARY_API_KEY
